/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AnimatedBannerComponent {
        "animation": string;
        "background": string;
        "color": string;
        "fontSize": number;
        "height": number;
        "loop": boolean;
        "text": string;
        "width": number;
    }
}
declare global {
    interface HTMLAnimatedBannerComponentElement extends Components.AnimatedBannerComponent, HTMLStencilElement {
    }
    var HTMLAnimatedBannerComponentElement: {
        prototype: HTMLAnimatedBannerComponentElement;
        new (): HTMLAnimatedBannerComponentElement;
    };
    interface HTMLElementTagNameMap {
        "animated-banner-component": HTMLAnimatedBannerComponentElement;
    }
}
declare namespace LocalJSX {
    interface AnimatedBannerComponent {
        "animation"?: string;
        "background"?: string;
        "color"?: string;
        "fontSize"?: number;
        "height"?: number;
        "loop"?: boolean;
        "text"?: string;
        "width"?: number;
    }
    interface IntrinsicElements {
        "animated-banner-component": AnimatedBannerComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "animated-banner-component": LocalJSX.AnimatedBannerComponent & JSXBase.HTMLAttributes<HTMLAnimatedBannerComponentElement>;
        }
    }
}
